import jsLogo from "../assets/images/js.jpg"
import htmlLogo from "../assets/images/html.png"
import tailwindLogo from "../assets/images/tailwind.png"
import phpLogo from "../assets/images/php.png"
import cssLogo from "../assets/images/css.png"
import reactLogo from "../assets/images/react.jpg"
import sqlLogo from "../assets/images/sql.jpg"
import bootstrapLogo from "../assets/images/bootstrap.png"
// import pythonLogo from "../assets/images/py.jpg"
// import angularLogo from "../assets/images/angular.jpg"
// import csharpLogo from "../assets/images/csharp.jpg"

export const coursesData = [
    {
        imageSrc: jsLogo,
        alt: "jsCourse",
        title: "Javascript دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 200000,
        progress: 75,
    },
    {
        imageSrc: htmlLogo,
        alt: "htmlCourse",
        title: "Html دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 55500000,
        progress: 35,
    },
    {
        imageSrc: tailwindLogo,
        alt: "tailwindCourse",
        title: "Tailwindcss دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/3/30",
        terminationDate: "2023/3/25",
        price: 125000,
        progress: 50,
    },
    {
        imageSrc: phpLogo,
        alt: "phpCourse",
        title: "PHP دوره",
        tutor: "میلاد محمدی",
        capacity: "۴۵",
        startDate: "2020/1/12",
        terminationDate: "2020/5/12",
        price: 2000000,
        progress: 100,
    },
    {
        imageSrc: reactLogo,
        alt: "reactCourse",
        title: "React دوره",
        tutor: "صدف رضایی",
        capacity: "۲۵",
        startDate: "2021/3/4",
        terminationDate: "2021/5/4",
        price: 6500000,
        progress: 85,
    },
    {
        imageSrc: cssLogo,
        alt: "cssCourse",
        title: "CSS دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2022/10/10",
        terminationDate: "2022/11/10",
        price: 299999,
        progress: 90,
    },
    {
        imageSrc: bootstrapLogo,
        alt: "sassCourse",
        title: "SASS دوره",
        tutor: "سارا اصفهانی",
        capacity: "۵۰",
        startDate: "2022/3/9",
        terminationDate: "2023/7/9",
        price: 399999,
        progress: 25,
    },
    {
        imageSrc: sqlLogo,
        alt: "sqlCourse",
        title: "SQL دوره",
        tutor: "میلاد عباسی",
        capacity: "۴۰",
        startDate: "2022/3/20",
        terminationDate: "2022/4/25",
        price: 1200000,
        progress: 100,
    },
    // {
    //     imageSrc: pythonLogo,
    //     alt: "pythonCourse",
    //     title: "Python دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۶۰",
    //     startDate: "2020/8/20",
    //     terminationDate: "2021/1/25",
    //     price: 1500000,
    //     progress: 100,
    // },
    // {
    //     imageSrc: angularLogo,
    //     alt: "angularCourse",
    //     title: "Angualr دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۴۰",
    //     startDate: "2021/1/5",
    //     terminationDate: "2021/4/20",
    //     price: 1200000,
    //     progress: 25,
    // },
    // {
    //     imageSrc: csharpLogo,
    //     alt: "csharpCourse",
    //     title: "C# دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۲۵",
    //     startDate: "2021/3/3",
    //     terminationDate: "2021/4/20",
    //     price: 600000,
    //     progress: 40,
    // },
    // {
    //     imageSrc: htmlLogo,
    //     alt: "htmlCourse",
    //     title: "Html دوره",
    //     tutor: "رضا عباسی",
    //     capacity: "۴۰",
    //     startDate: "2022/2/12",
    //     terminationDate: "2022/3/20",
    //     price: 55500000,
    //     progress: 35,
    // },
    // {
    //     imageSrc: tailwindLogo,
    //     alt: "tailwindCourse",
    //     title: "Tailwindcss دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۳۰",
    //     startDate: "2023/3/30",
    //     terminationDate: "2023/3/25",
    //     price: 125000,
    //     progress: 50,
    // },
    // {
    //     imageSrc: phpLogo,
    //     alt: "phpCourse",
    //     title: "PHP دوره",
    //     tutor: "میلاد محمدی",
    //     capacity: "۴۵",
    //     startDate: "2020/1/12",
    //     terminationDate: "2020/5/12",
    //     price: 2000000,
    //     progress: 100,
    // },
    // {
    //     imageSrc: reactLogo,
    //     alt: "reactCourse",
    //     title: "React دوره",
    //     tutor: "صدف رضایی",
    //     capacity: "۲۵",
    //     startDate: "2021/3/4",
    //     terminationDate: "2021/5/4",
    //     price: 6500000,
    //     progress: 85,
    // },
    // {
    //     imageSrc: cssLogo,
    //     alt: "cssCourse",
    //     title: "CSS دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۶۰",
    //     startDate: "2022/10/10",
    //     terminationDate: "2022/11/10",
    //     price: 299999,
    //     progress: 90,
    // },
    // {
    //     imageSrc: angularLogo,
    //     alt: "angularCourse",
    //     title: "Angualr دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۴۰",
    //     startDate: "2021/1/5",
    //     terminationDate: "2021/4/20",
    //     price: 1200000,
    //     progress: 25,
    // },
    // {
    //     imageSrc: csharpLogo,
    //     alt: "csharpCourse",
    //     title: "C# دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۲۵",
    //     startDate: "2021/3/3",
    //     terminationDate: "2021/4/20",
    //     price: 600000,
    //     progress: 40,
    // },
    // {
    //     imageSrc: htmlLogo,
    //     alt: "htmlCourse",
    //     title: "Html دوره",
    //     tutor: "رضا عباسی",
    //     capacity: "۴۰",
    //     startDate: "2022/2/12",
    //     terminationDate: "2022/3/20",
    //     price: 55500000,
    //     progress: 35,
    // },
    // {
    //     imageSrc: tailwindLogo,
    //     alt: "tailwindCourse",
    //     title: "Tailwindcss دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۳۰",
    //     startDate: "2023/3/30",
    //     terminationDate: "2023/3/25",
    //     price: 125000,
    //     progress: 50,
    // },
    // {
    //     imageSrc: pythonLogo,
    //     alt: "pythonCourse",
    //     title: "Python دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۶۰",
    //     startDate: "2020/8/20",
    //     terminationDate: "2021/1/25",
    //     price: 1500000,
    //     progress: 100,
    // },
    // {
    //     imageSrc: angularLogo,
    //     alt: "angularCourse",
    //     title: "Angualr دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۴۰",
    //     startDate: "2021/1/5",
    //     terminationDate: "2021/4/20",
    //     price: 1200000,
    //     progress: 25,
    // },
    // {
    //     imageSrc: csharpLogo,
    //     alt: "csharpCourse",
    //     title: "C# دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۲۵",
    //     startDate: "2021/3/3",
    //     terminationDate: "2021/4/20",
    //     price: 600000,
    //     progress: 40,
    // },

]