import jsLogo from "../assets/images/js.jpg"
import htmlLogo from "../assets/images/html.png"
import tailwindLogo from "../assets/images/tailwind.png"
import phpLogo from "../assets/images/php.png"
import cssLogo from "../assets/images/css.png"
import reactLogo from "../assets/images/react.jpg"
import sqlLogo from "../assets/images/sql.jpg"
import bootstrapLogo from "../assets/images/bootstrap.png"
import pythonLogo from "../assets/images/python.jpeg"
import angularLogo from "../assets/images/angular.jpg"
import csharpLogo from "../assets/images/csharp.jpeg"
import tsLogo from "../assets/images/ts.image"
import goLogo from "../assets/images/go.webp"
import swiftLogo from "../assets/images/swift.jpeg"
import rubyLogo from "../assets/images/ruby.png"
import kotlinLogo from "../assets/images/kotlin.png"
import rustLogo from "../assets/images/rust.webp"
import javaLogo from "../assets/images/java.jpg"
import nextLogo from "../assets/images/next.jpeg"
import vuejsLogo from "../assets/images/vue.jpeg"
import nodeLogo from "../assets/images/node.png"
import viteLogo from "../assets/images/vite.webp"
import reduxLogo from "../assets/images/redux.jpg"
import jqueryLogo from "../assets/images/jquery.png"
import sassLogo from "../assets/images/sass.jpg"
import webpackLogo from "../assets/images/webpack.jpg"
import laravelLogo from "../assets/images/laravel.png"

export const coursesData = [
    {
        imageSrc: nextLogo,
        alt: "nextCourse",
        title: "NEXT.js دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2300000,
        progress: 75,
    },
    {
        imageSrc: vuejsLogo,
        alt: "vueCourse",
        title: "Vuejs دوره",
        tutor: "سارا اصفهانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2150000,
        progress: 75,
    },
    {
        imageSrc: tsLogo,
        alt: "tsCourse",
        title: "Typescript دوره",
        tutor: "صدف رضایی",
        capacity: "۳۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2200000,
        progress: 75,
    },
    {
        imageSrc: rustLogo,
        alt: "rustCourse",
        title: "Rust دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 1550000,
        progress: 75,
    },
    {
        imageSrc: cssLogo,
        alt: "cssCourse",
        title: "CSS دوره",
        tutor: "میلاد محمدی",
        capacity: "۶۰",
        startDate: "2022/10/10",
        terminationDate: "2022/11/10",
        price: 299999,
        progress: 90,
    },
    {
        imageSrc: rubyLogo,
        alt: "rubyCourse",
        title: "Ruby دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 1000000,
        progress: 75,
    },
    {
        imageSrc: bootstrapLogo,
        alt: "bootstrapCourse",
        title: "Bootstrap دوره",
        tutor: "سارا اصفهانی",
        capacity: "۵۰",
        startDate: "2022/3/9",
        terminationDate: "2023/7/9",
        price: 399999,
        progress: 25,
    },
    {
        imageSrc: sqlLogo,
        alt: "sqlCourse",
        title: "SQL دوره",
        tutor: "میلاد عباسی",
        capacity: "۴۰",
        startDate: "2022/3/20",
        terminationDate: "2022/4/25",
        price: 1200000,
        progress: 100,
    },
    {
        imageSrc: pythonLogo,
        alt: "pythonCourse",
        title: "Python دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2020/8/20",
        terminationDate: "2021/1/25",
        price: 1500000,
        progress: 100,
    },
    {
        imageSrc: csharpLogo,
        alt: "csharpCourse",
        title: "C# دوره",
        tutor: "علی زمانی",
        capacity: "۲۵",
        startDate: "2021/3/3",
        terminationDate: "2021/4/20",
        price: 600000,
        progress: 40,
    },
    {
        imageSrc: angularLogo,
        alt: "angularCourse",
        title: "Angualr دوره",
        tutor: "سارا اصفهانی",
        capacity: "۴۰",
        startDate: "2021/1/5",
        terminationDate: "2021/4/20",
        price: 1200000,
        progress: 25,
    },
    {
        imageSrc: htmlLogo,
        alt: "htmlCourse",
        title: "Html دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 555000,
        progress: 35,
    },
    {
        imageSrc: tailwindLogo,
        alt: "tailwindCourse",
        title: "Tailwindcss دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/3/30",
        terminationDate: "2023/3/25",
        price: 325000,
        progress: 50,
    },
    {
        imageSrc: goLogo,
        alt: "goCourse",
        title: "GO دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 1500000,
        progress: 35,
    },
    {
        imageSrc: swiftLogo,
        alt: "swiftCourse",
        title: "Swift دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/4/30",
        terminationDate: "2023/3/25",
        price: 450000,
        progress: 50,
    },
    {
        imageSrc: phpLogo,
        alt: "phpCourse",
        title: "PHP دوره",
        tutor: "میلاد محمدی",
        capacity: "۴۵",
        startDate: "2020/1/12",
        terminationDate: "2020/5/12",
        price: 2000000,
        progress: 100,
    },
    {
        imageSrc: kotlinLogo,
        alt: "kotlinCourse",
        title: "Kotlin دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 525000,
        progress: 100,
    },
    {
        imageSrc: reactLogo,
        alt: "reactCourse",
        title: "React دوره",
        tutor: "صدف رضایی",
        capacity: "۲۵",
        startDate: "2021/3/4",
        terminationDate: "2021/5/4",
        price: 6500000,
        progress: 85,
    },
    {
        imageSrc: javaLogo,
        alt: "javaCourse",
        title: "Java دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2020/8/20",
        terminationDate: "2021/1/25",
        price: 450000,
        progress: 100,
    },
    {
        imageSrc: jsLogo,
        alt: "jsCourse",
        title: "Javascript دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2000000,
        progress: 100,
    },
    {
        imageSrc: nodeLogo,
        alt: "nodeCourse",
        title: "Nodejs دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 1455000,
        progress: 35,
    },
    {
        imageSrc: viteLogo,
        alt: "viteCourse",
        title: "Vitejs دوره",
        tutor: "علی زمانی",
        capacity: "۲۵",
        startDate: "2021/3/3",
        terminationDate: "2021/4/20",
        price: 650000,
        progress: 40,
    },
    {
        imageSrc: reduxLogo,
        alt: "reduxCourse",
        title: "Redux دوره",
        tutor: "سارا اصفهانی",
        capacity: "۴۰",
        startDate: "2021/1/5",
        terminationDate: "2021/4/20",
        price: 500000,
        progress: 100,
    },
    {
        imageSrc: jqueryLogo,
        alt: "jqueryCourse",
        title: "JQuery دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 230000,
        progress: 75,
    },
    {
        imageSrc: sassLogo,
        alt: "sassCourse",
        title: "Sass دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 755000,
        progress: 35,
    },
    {
        imageSrc: webpackLogo,
        alt: "webpackCourse",
        title: "Webpack دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/5/30",
        terminationDate: "2023/3/25",
        price: 345000,
        progress: 50,
    },
    {
        imageSrc: laravelLogo,
        alt: "laravelCourse",
        title: "Laravel دوره",
        tutor: "میلاد محمدی",
        capacity: "۴۵",
        startDate: "2020/1/12",
        terminationDate: "2020/5/12",
        price: 2000000,
        progress: 100,
    },
    {
        imageSrc: reactLogo,
        alt: "reactCourse",
        title: "React دوره",
        tutor: "صدف رضایی",
        capacity: "۲۵",
        startDate: "2021/3/4",
        terminationDate: "2021/5/4",
        price: 65000,
        progress: 100,
    },
    {
        imageSrc: cssLogo,
        alt: "cssCourse",
        title: "CSS دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2022/10/10",
        terminationDate: "2022/11/10",
        price: 299999,
        progress: 90,
    },
    {
        imageSrc: bootstrapLogo,
        alt: "sassCourse",
        title: "Bootstrap دوره",
        tutor: "سارا اصفهانی",
        capacity: "۵۰",
        startDate: "2022/3/9",
        terminationDate: "2023/7/9",
        price: 399999,
        progress: 100,
    },
    {
        imageSrc: nextLogo,
        alt: "nextCourse",
        title: "NEXTjs دوره",
        tutor: "میلاد عباسی",
        capacity: "۴۰",
        startDate: "2022/3/20",
        terminationDate: "2022/4/25",
        price: 1200000,
        progress: 100,
    },
    {
        imageSrc: jsLogo,
        alt: "jsCourse",
        title: "Javascript دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2020/8/20",
        terminationDate: "2021/1/25",
        price: 160000,
        progress: 100,
    },
]