//courses page assets
import jsLogo from "../assets/images/js.jpg"
import htmlLogo from "../assets/images/html.png"
import tailwindLogo from "../assets/images/tailwind.png"
import phpLogo from "../assets/images/php.png"
import cssLogo from "../assets/images/css.png"
import reactLogo from "../assets/images/react.jpg"
import sqlLogo from "../assets/images/sql.jpg"
import bootstrapLogo from "../assets/images/bootstrap.png"
import pythonLogo from "../assets/images/python.jpeg"
import angularLogo from "../assets/images/angular.jpg"
import csharpLogo from "../assets/images/csharp.jpeg"
import tsLogo from "../assets/images/ts.image"
import goLogo from "../assets/images/go.webp"
import swiftLogo from "../assets/images/swift.jpeg"
import rubyLogo from "../assets/images/ruby.png"
import kotlinLogo from "../assets/images/kotlin.png"
import rustLogo from "../assets/images/rust.webp"
import javaLogo from "../assets/images/java.jpg"
import nextLogo from "../assets/images/next.jpeg"
import vuejsLogo from "../assets/images/vue.jpeg"
import nodeLogo from "../assets/images/node.png"
import viteLogo from "../assets/images/vite.webp"
import reduxLogo from "../assets/images/redux.jpg"
import jqueryLogo from "../assets/images/jquery.png"
import sassLogo from "../assets/images/sass.jpg"
import webpackLogo from "../assets/images/webpack.jpg"
import laravelLogo from "../assets/images/laravel.png"

// course hero section assets
import jsHero from '../assets/images/course-logo.png';
import jsModal from '../assets/images/js-logo.png';
const HTMLHero = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Fhtml-5_174854&psig=AOvVaw2Y_BeyuLAJLRVO_tmujlM9&ust=1675342527466000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCOjQx7Ov9PwCFQAAAAAdAAAAABAJ";
const cssHero = "https://www.freepnglogos.com/uploads/html5-logo-png/html5-logo-css-logo-png-transparent-svg-vector-bie-supply-9.png";
const tailwindHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Tailwind_CSS_Logo.svg/2048px-Tailwind_CSS_Logo.svg.png";
const PHPHero = "https://www.php.net/images/logos/new-php-logo.svg";
const reactHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png";
const MySQLHero = "https://1000logos.net/wp-content/uploads/2020/08/MySQL-Logo.png";
const bootstrapHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Bootstrap_logo.svg/1200px-Bootstrap_logo.svg.png";
const pythonHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/1200px-Python-logo-notext.svg.png";
const angularHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/1200px-Angular_full_color_logo.svg.png";
const csharpHero = "https://seeklogo.com/images/C/c-sharp-c-logo-02F17714BA-seeklogo.com.png";
const tsHero = "https://upload.wikimedia.org/wikipedia/commons/4/4c/Typescript_logo_2020.svg";
const goHero = "https://i.etsystatic.com/15149849/r/il/c0da64/2032115144/il_fullxfull.2032115144_gp7m.jpg";
const goModal = "https://go.dev/blog/go-brand/Go-Logo/PNG/Go-Logo_Blue.png"
const swiftHero = "https://developer.apple.com/swift/images/swift-og.png";
const rubyHero = "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ruby_logo.png";
const kotlinHero = "https://upload.wikimedia.org/wikipedia/commons/7/74/Kotlin_Icon.png";
const rustHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/1024px-Rust_programming_language_black_logo.svg.png";
const rustModal = "https://e7.pngegg.com/pngimages/114/914/png-clipart-rust-programming-language-logo-machine-learning-haskell-crab-animals-cartoon.png"
const JavaHero = "https://upload.wikimedia.org/wikipedia/en/3/30/Java_programming_language_logo.svg";
const nextHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/800px-Nextjs-logo.svg.png";
const nextModal = "https://seeklogo.com/images/N/next-js-icon-logo-EE302D5DBD-seeklogo.com.png";
const vueHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1200px-Vue.js_Logo_2.svg.png";
const nodeHero = "https://pluralsight2.imgix.net/paths/images/nodejs-45adbe594d.png";
const viteHero = "https://vitejs.dev/logo-with-shadow.png";
const reduxHero = "https://www.howtogeek.com/wp-content/uploads/csit/2021/02/99128fa6.jpg?height=200p&trim=2,2,2,2";
const jqueryHero = "https://www.chicagocomputerclasses.com/wp-content/uploads/2016/01/jquery.gif";
const sassHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Sass_Logo_Color.svg/1200px-Sass_Logo_Color.svg.png";
const webpackHero = "https://webpack.js.org/icon-pwa-512x512.d3dae4189855b3a72ff9.png";
const laravelHero = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Laravel.svg/1200px-Laravel.svg.png";


const DESCRIPTION = "امروزه به دلیل آن که ارتباطات فضای مجازی رونق زیادی یافته است طراحی یک سایت به شکل مناسب و مورد پسند کاربران متفاوت اهمیت بالایی یافته است. به همین جهت صاحبان سرمایه و کار برای رونق کار خود به دنبال طراحان حرفه ای برای طراحی سایتی مناسب و کارآمد هستند. لذا یادگیری روش های مناسب و به روز طراحی سایت مورد توجه بسیاری از علاقه مندان و کارجویان قرار گرفته است. جاوا اسکریپت زبان برنامه نویسی مفسری در سمت کلاینت است که می توان بوسیله سایتی مناسب و کارآمد هستند. لذا یادگیری روش های مناسب و به روز طراحی سایت مورد توجه بسیاری از علاقه مندان و کارجویان قرار گرفته است. جاوا اسکریپت زبان برنامه نویسی مفسری در سمت کلاینت است که می توان بوسیله";

const BENEFITS = (title) => [
    {
        id: "123",
        title: `آشنایی با زبان برنامه نویسی ${title}`,
        context:
            "در پایان این دوره ی آموزشی ، شما دانشجوی گرامی ، قادر به فهمی عمیق و مناسب نسبت به این زبان خواهید بود"
    },
    {
        id: "124",
        title: `آشنایی با زبان برنامه نویسی ${title}`,
        context:
            "در پایان این دوره ی آموزشی ، شما دانشجوی گرامی ، قادر به فهمی عمیق و مناسب نسبت به این زبان خواهید بود"
    },
    {
        id: "321",
        title: `آشنایی با زبان برنامه نویسی ${title}`,
        context:
            "در پایان این دوره ی آموزشی ، شما دانشجوی گرامی ، قادر به فهمی عمیق و مناسب نسبت به این زبان خواهید بود"
    }
]


export const coursesData = [
    {
        imageSrc: nextLogo,
        alt: "nextCourse",
        title: "NEXT.js دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2300000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("نکست جی اس"),
        id: "bf047201-3369-4506-8425-bf9c3f8ec298",
        heroSrc: nextHero,
        modalSrc: nextModal,
    },
    {
        imageSrc: vuejsLogo,
        alt: "vueCourse",
        title: "Vue.js دوره",
        tutor: "سارا اصفهانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2150000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("ویو جی اس"),
        id: "5e278376-ff08-48b7-a9a4-a5ede91c98e5",
        heroSrc: vueHero,
        modalSrc: vueHero,
    },
    {
        imageSrc: tsLogo,
        alt: "tsCourse",
        title: "Typescript دوره",
        tutor: "صدف رضایی",
        capacity: "۳۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2200000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("تایپ اسکریپت"),
        id: "6e2069c9-06c4-42f7-ab47-3d81fba3df0a",
        heroSrc: tsHero,
        modalSrc: tsHero,
    },
    {
        imageSrc: rustLogo,
        alt: "rustCourse",
        title: "Rust دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 1550000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("راست"),
        id: "817e3420-4087-4cf8-bbb0-e0df1abdbb18",
        heroSrc: rustHero,
        modalSrc: rustModal,
    },
    {
        imageSrc: cssLogo,
        alt: "cssCourse",
        title: "CSS دوره",
        tutor: "میلاد محمدی",
        capacity: "۶۰",
        startDate: "2022/10/10",
        terminationDate: "2022/11/10",
        price: 299999,
        progress: 90,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("سی اس اس"),
        id: "9d2a00a2-f974-4972-b048-8b5570e298b7",
        heroSrc: cssHero,
        modalSrc: cssHero,
    },
    {
        imageSrc: rubyLogo,
        alt: "rubyCourse",
        title: "Ruby دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 1000000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("روبی"),
        id: "f64435fc-7248-4051-9684-4f97598d597c",
        heroSrc: rubyHero,
        modalSrc: rubyHero,
    },
    {
        imageSrc: bootstrapLogo,
        alt: "bootstrapCourse",
        title: "Bootstrap دوره",
        tutor: "سارا اصفهانی",
        capacity: "۵۰",
        startDate: "2022/3/9",
        terminationDate: "2023/7/9",
        price: 399999,
        progress: 25,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("بوت استرپ"),
        id: "56745e7f-9636-442b-b187-884dec92422b",
        heroSrc: bootstrapHero,
        modalSrc: bootstrapHero,
    },
    {
        imageSrc: sqlLogo,
        alt: "mysqlCourse",
        title: "MYSQL دوره",
        tutor: "میلاد عباسی",
        capacity: "۴۰",
        startDate: "2022/3/20",
        terminationDate: "2022/4/25",
        price: 1200000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("مای اس کیو ال"),
        id: "1daec968-f0f9-4fa9-b542-b3e2f4e70b4e",
        heroSrc: MySQLHero,
        modalSrc: MySQLHero,
    },
    {
        imageSrc: pythonLogo,
        alt: "pythonCourse",
        title: "Python دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2020/8/20",
        terminationDate: "2021/1/25",
        price: 1500000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("پایتون"),
        id: "c8af881b-594c-4c09-8726-9208f92a6289",
        heroSrc: pythonHero,
        modalSrc: pythonHero,
    },
    {
        imageSrc: csharpLogo,
        alt: "csharpCourse",
        title: "C# دوره",
        tutor: "علی زمانی",
        capacity: "۲۵",
        startDate: "2021/3/3",
        terminationDate: "2021/4/20",
        price: 600000,
        progress: 40,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("سی شارپ"),
        id: "9d5470a7-729f-48e7-9624-c779564dc9e1",
        heroSrc: csharpHero,
        modalSrc: csharpHero,
    },
    {
        imageSrc: angularLogo,
        alt: "angularCourse",
        title: "Angualr دوره",
        tutor: "سارا اصفهانی",
        capacity: "۴۰",
        startDate: "2021/1/5",
        terminationDate: "2021/4/20",
        price: 1200000,
        progress: 25,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("انگولار"),
        id: "3169c349-efe2-419a-9cd1-9d8141c8e0b8",
        heroSrc: angularHero,
        modalSrc: angularHero,
    },
    {
        imageSrc: htmlLogo,
        alt: "htmlCourse",
        title: "Html دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 555000,
        progress: 35,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("اچ تی ام ال"),
        id: "cde9aa2a-071e-4271-a41e-e9ef84c6743d",
        heroSrc: HTMLHero,
        modalSrc: HTMLHero,
    },
    {
        imageSrc: tailwindLogo,
        alt: "tailwindCourse",
        title: "Tailwindcss دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/3/30",
        terminationDate: "2023/3/25",
        price: 325000,
        progress: 50,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("تیلویند"),
        id: "83013b70-f90e-40f6-9d32-4adb218a9736",
        heroSrc: tailwindHero,
        modalSrc: tailwindHero,
    },
    {
        imageSrc: goLogo,
        alt: "goCourse",
        title: "GO دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 1500000,
        progress: 35,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("گو لنگ"),
        id: "83b3b938-3180-4f41-b81f-230a8c942a03",
        heroSrc: goHero,
        modalSrc: goModal,
    },
    {
        imageSrc: swiftLogo,
        alt: "swiftCourse",
        title: "Swift دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/4/30",
        terminationDate: "2023/3/25",
        price: 450000,
        progress: 50,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("سوئیفت"),
        id: "2a95e9fc-500a-417c-8844-78b80f092ba6",
        heroSrc: swiftHero,
        modalSrc: swiftHero,
    },
    {
        imageSrc: phpLogo,
        alt: "phpCourse",
        title: "PHP دوره",
        tutor: "میلاد محمدی",
        capacity: "۴۵",
        startDate: "2020/1/12",
        terminationDate: "2020/5/12",
        price: 2000000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("پی اچ پی"),
        id: "1881ee84-612f-4409-aff6-109ee51694ce",
        heroSrc: PHPHero,
        modalSrc: PHPHero,
    },
    {
        imageSrc: kotlinLogo,
        alt: "kotlinCourse",
        title: "Kotlin دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 525000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("کاتلین"),
        id: "95e90187-e067-465e-909a-378d9d841b86",
        heroSrc: kotlinHero,
        modalSrc: kotlinHero,
    },
    {
        imageSrc: reactLogo,
        alt: "reactCourse",
        title: "React دوره",
        tutor: "صدف رضایی",
        capacity: "۲۵",
        startDate: "2021/3/4",
        terminationDate: "2021/5/4",
        price: 6500000,
        progress: 85,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("ری اکت"),
        id: "b87cb02c-93b0-4e34-9c62-5476a5fe48ef",
        heroSrc: reactHero,
        modalSrc: reactHero,
    },
    {
        imageSrc: javaLogo,
        alt: "javaCourse",
        title: "Java دوره",
        tutor: "علی زمانی",
        capacity: "۶۰",
        startDate: "2020/8/20",
        terminationDate: "2021/1/25",
        price: 450000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("جاوا"),
        id: "0bbc798d-5c5f-417a-b987-7a795f427c99",
        heroSrc: JavaHero,
        modalSrc: JavaHero,
    },
    {
        imageSrc: jsLogo,
        alt: "jsCourse",
        title: "Javascript دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 2000000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("جاوا اسکریپت"),
        id: "70ce3ded-c3fd-46e9-9f6b-89ff5ca1c894",
        heroSrc: jsHero,
        modalSrc: jsModal,
    },
    {
        imageSrc: nodeLogo,
        alt: "nodeCourse",
        title: "Nodejs دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 1455000,
        progress: 35,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("نود جی اس"),
        id: "1d96c910-9255-4b8b-ad36-1812ad9bc326",
        heroSrc: nodeHero,
        modalSrc: nodeHero,
    },
    {
        imageSrc: viteLogo,
        alt: "viteCourse",
        title: "Vitejs دوره",
        tutor: "علی زمانی",
        capacity: "۲۵",
        startDate: "2021/3/3",
        terminationDate: "2021/4/20",
        price: 650000,
        progress: 40,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("ویت"),
        id: "86bcac98-810c-4362-8b6b-9a178ca9716f",
        heroSrc: viteHero,
        modalSrc: viteHero,
    },
    {
        imageSrc: reduxLogo,
        alt: "reduxCourse",
        title: "Redux دوره",
        tutor: "سارا اصفهانی",
        capacity: "۴۰",
        startDate: "2021/1/5",
        terminationDate: "2021/4/20",
        price: 500000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("ریداکس"),
        id: "bb6a0f48-07db-46ea-ae21-6f3fd844fcde",
        heroSrc: reduxHero,
        modalSrc: reduxHero,
    },
    {
        imageSrc: jqueryLogo,
        alt: "jqueryCourse",
        title: "JQuery دوره",
        tutor: "علی زمانی",
        capacity: "۲۰",
        startDate: "2023/3/3",
        terminationDate: "2023/5/27",
        price: 230000,
        progress: 75,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS(" جی کوئری"),
        id: "1e2f6114-b38c-4434-ad68-ae36ab089b3d",
        heroSrc: jqueryHero,
        modalSrc: jqueryHero,
    },
    {
        imageSrc: sassLogo,
        alt: "sassCourse",
        title: "Sass دوره",
        tutor: "رضا عباسی",
        capacity: "۴۰",
        startDate: "2022/2/12",
        terminationDate: "2022/3/20",
        price: 755000,
        progress: 35,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("sass"),
        id: "7c9c5603-054b-41ac-96e8-32ee0dc26c15",
        heroSrc: sassHero,
        modalSrc: sassHero,
    },
    {
        imageSrc: webpackLogo,
        alt: "webpackCourse",
        title: "Webpack دوره",
        tutor: "سارا اصفهانی",
        capacity: "۳۰",
        startDate: "2023/5/30",
        terminationDate: "2023/3/25",
        price: 345000,
        progress: 50,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("وب پک"),
        id: "c98ae21c-cbe7-4a42-9bdd-41e42967a270",
        heroSrc: webpackHero,
        modalSrc: webpackHero,
    },
    {
        imageSrc: laravelLogo,
        alt: "laravelCourse",
        title: "Laravel دوره",
        tutor: "میلاد محمدی",
        capacity: "۴۵",
        startDate: "2020/1/12",
        terminationDate: "2020/5/12",
        price: 2000000,
        progress: 100,
        students_count: "۲۳",
        rating: 3,
        description: DESCRIPTION,
        discount: 20,
        benefits: BENEFITS("لاراول"),
        id: "a5ebfff7-d12e-4101-9750-451b7923a695",
        heroSrc: laravelHero,
        modalSrc: laravelHero,
    },
    // {
    //     imageSrc: reactLogo,
    //     alt: "reactCourse",
    //     title: "React دوره",
    //     tutor: "صدف رضایی",
    //     capacity: "۲۵",
    //     startDate: "2021/3/4",
    //     terminationDate: "2021/5/4",
    //     price: 65000,
    //     progress: 100,
    //     students_count:2"۲۳"
    //     rating:3,
    //     description:DESCRIPTION,
    //     discount:20,
    //     benefits:BENEFITS,
    //     id:"d09adade-a58a-48c8-b14e-c9147621bd92",
    //     heroSrc:"",
    //     modalSrc:"",
    // },
    // {
    //     imageSrc: cssLogo,
    //     alt: "cssCourse",
    //     title: "CSS دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۶۰",
    //     startDate: "2022/10/10",
    //     terminationDate: "2022/11/10",
    //     price: 299999,
    //     progress: 90,
    //     students_count:2"۲۳"
    //     rating:3,
    //     description:DESCRIPTION,
    //     discount:20,
    //     benefits:BENEFITS,
    //     id:"328fee41-ecc0-4dab-88a4-5b48888b61ae",
    //     heroSrc:"",
    //     modalSrc:"",
    // },
    // {
    //     imageSrc: bootstrapLogo,
    //     alt: "sassCourse",
    //     title: "Bootstrap دوره",
    //     tutor: "سارا اصفهانی",
    //     capacity: "۵۰",
    //     startDate: "2022/3/9",
    //     terminationDate: "2023/7/9",
    //     price: 399999,
    //     progress: 100,
    //     students_count:2"۲۳"
    //     rating:3,
    //     description:DESCRIPTION,
    //     discount:20,
    //     benefits:BENEFITS,
    //     id:"ca6f91d6-323d-4acb-baa5-7daecf65554b",
    //     heroSrc:"",
    //     modalSrc:"",
    // },
    // {
    //     imageSrc: nextLogo,
    //     alt: "nextCourse",
    //     title: "NEXTjs دوره",
    //     tutor: "میلاد عباسی",
    //     capacity: "۴۰",
    //     startDate: "2022/3/20",
    //     terminationDate: "2022/4/25",
    //     price: 1200000,
    //     progress: 100,
    //     students_count:2"۲۳"
    //     rating:3,
    //     description:DESCRIPTION,
    //     discount:20,
    //     benefits:BENEFITS,
    //     id:"bbf53cfa-a5f7-4142-9a56-7258fb1b2513",
    //     heroSrc:"",
    //     modalSrc:"",
    // },
    // {
    //     imageSrc: jsLogo,
    //     alt: "jsCourse",
    //     title: "Javascript دوره",
    //     tutor: "علی زمانی",
    //     capacity: "۶۰",
    //     startDate: "2020/8/20",
    //     terminationDate: "2021/1/25",
    //     price: 160000,
    //     progress: 100,
    //     students_count:2"۲۳"
    //     rating:3,
    //     description:DESCRIPTION,
    //     discount:20,
    //     benefits:BENEFITS,
    //     id:"8472aeb2-1a72-416c-a68a-39e62f139fab",
    //     heroSrc:"",
    //     modalSrc:"",
    // },
]